# Generated by Django 3.2.5 on 2021-07-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
    ]
