# Generated by Django 3.2.5 on 2021-07-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0001_initial'),
        ('Contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.IntegerField(blank=True, null=True)),
                ('jobTitle', models.CharField(max_length=70)),
                ('jobPrice', models.IntegerField(null=True)),
                ('jobtime', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.companies')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contractor.contractor')),
            ],
        ),
    ]
